<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PresensiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $presensiData = [
            [
                'karyawan_id' => 1,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 2,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '05:19:13',
                'jam_pulang' => '18:24:42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 3,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '05:19:37',
                'jam_pulang' => '18:24:46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 4,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '05:19:38',
                'jam_pulang' => '18:24:38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 5,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 6,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 7,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '05:19:13',
                'jam_pulang' => '18:24:42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 8,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '05:19:37',
                'jam_pulang' => '18:24:46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 9,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '05:19:38',
                'jam_pulang' => '18:24:38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 10,
                'kloter_id' => 1,
                'tanggal' => '2025-04-24',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 1,
                'kloter_id' => 1,
                'tanggal' => '2025-04-25',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 2,
                'kloter_id' => 1,
                'tanggal' => '2025-04-25',
                'jam_masuk' => '05:19:13',
                'jam_pulang' => '18:24:42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 4,
                'kloter_id' => 1,
                'tanggal' => '2025-04-25',
                'jam_masuk' => '05:19:38',
                'jam_pulang' => '18:24:38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 5,
                'kloter_id' => 1,
                'tanggal' => '2025-04-25',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 6,
                'kloter_id' => 1,
                'tanggal' => '2025-04-25',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 7,
                'kloter_id' => 1,
                'tanggal' => '2025-04-25',
                'jam_masuk' => '05:19:13',
                'jam_pulang' => '18:24:42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 8,
                'kloter_id' => 1,
                'tanggal' => '2025-04-25',
                'jam_masuk' => '05:19:37',
                'jam_pulang' => '18:24:46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 9,
                'kloter_id' => 1,
                'tanggal' => '2025-04-25',
                'jam_masuk' => '05:19:38',
                'jam_pulang' => '18:24:38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 10,
                'kloter_id' => 1,
                'tanggal' => '2025-04-25',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 1,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 2,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '05:19:13',
                'jam_pulang' => '18:24:42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 3,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '05:19:37',
                'jam_pulang' => '18:24:46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 4,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '05:19:38',
                'jam_pulang' => '18:24:38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 5,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 6,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 7,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '05:19:13',
                'jam_pulang' => '18:24:42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 8,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '05:19:37',
                'jam_pulang' => '18:24:46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 9,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '05:19:38',
                'jam_pulang' => '18:24:38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 10,
                'kloter_id' => 1,
                'tanggal' => '2025-04-26',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 1,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 2,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '05:19:13',
                'jam_pulang' => '18:24:42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 3,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '05:19:37',
                'jam_pulang' => '18:24:46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 4,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '05:19:38',
                'jam_pulang' => '18:24:38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 5,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 6,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 7,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '05:19:13',
                'jam_pulang' => '18:24:42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 8,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '05:19:37',
                'jam_pulang' => '18:24:46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 9,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '05:19:38',
                'jam_pulang' => '18:24:38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 10,
                'kloter_id' => 2,
                'tanggal' => '2025-04-27',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 1,
                'kloter_id' => 2,
                'tanggal' => '2025-04-28',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 3,
                'kloter_id' => 2,
                'tanggal' => '2025-04-28',
                'jam_masuk' => '05:19:37',
                'jam_pulang' => '18:24:46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 5,
                'kloter_id' => 2,
                'tanggal' => '2025-04-28',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 6,
                'kloter_id' => 2,
                'tanggal' => '2025-04-28',
                'jam_masuk' => '08:40:32',
                'jam_pulang' => '17:12:28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 7,
                'kloter_id' => 2,
                'tanggal' => '2025-04-28',
                'jam_masuk' => '05:19:13',
                'jam_pulang' => '18:24:42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 9,
                'kloter_id' => 2,
                'tanggal' => '2025-04-28',
                'jam_masuk' => '05:19:38',
                'jam_pulang' => '18:24:38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'karyawan_id' => 10,
                'kloter_id' => 2,
                'tanggal' => '2025-04-28',
                'jam_masuk' => '05:19:30',
                'jam_pulang' => '18:24:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('presensis')->insert($presensiData);
    }
}
